owners:
  - number: '233500850221'
    name: BG
    # If you type '/owner' and if isCreator is true, this number will be shown as the owner
    isCreator: true
    # This field below will be displayed in vcard
    messages:
      - content: Hello 
        label: Greetings
    # if only one of the title or org is filled, it will not appear on the vcard
    title: Main Creator 
    org: Andrew
    emails: 
      - bussinesbochilgaming@gmail.com
    urls:
      - https://github.com/BochilGaming
    
sticker:
  packname: Create stickers at wa.me/233500850221
  author: ©2023 Metro Bot

donations: 
  gopay: '233500850221'
  dana: '233500850221'
  saweria: https://saweria.co/BochilGaming
  # other donations with format Record<string, string>

# level multiplier, higher is harder to go to the next level
multiplier: 30

emoticons:
  # not case-sensitive. All keys will be processed to lowercase
  exp: 💫
  level: 🧬
  money: 💸

community: https://whatsapp.com/channel/0029VapJCy9GJP89oQIREA45
